### ISSUE TITLE
ideal test_patch size? 

### ISSUE THREAD

**Issue by DevashishPrasad** [hjSim/KOALAnet#3]
Thank you so much for this amazing work. And congratulations on the research paper accepted at CVPR.

I want to evaluate your models on the Set 5 dataset. However, when I ran the model (4X) with the default test_patch argument [1,1], the results were images with total noise. I don't know for sure what's the issue, but I tried changing the default test_patch argument to [2,2] and got the following results. It is a little better than totally noisy images. Changing test_patch size is affecting the resulting super-resolution image, so what should be the ideal value for the test_patch parameter?

![img_001](https://user-images.githubusercontent.com/37477321/159141643-c6b05667-ac1c-4a56-be37-4da9cc6917cd.png)
![img_002](https://user-images.githubusercontent.com/37477321/159141644-753f346a-191b-4c2c-adcb-9eea7c0a5049.png)
![img_003](https://user-images.githubusercontent.com/37477321/159141645-894222e2-3439-4426-8bee-68615e1ba08e.png)
![img_004](https://user-images.githubusercontent.com/37477321/159141646-d9ed78d8-59e0-4cad-8da2-623aa594197d.png)
![img_005](https://user-images.githubusercontent.com/37477321/159141647-f017df4e-f390-4426-937f-6c53c923b498.png)

As you can see the results do not look good. What am I missing here?

It will mean a lot if I can get any leads about what can be going wrong here.

Thank you in advance!

**Comment by DevashishPrasad** [comment]
Solved!! It is running perfectly on Colab

There is some issue with my laptop CUDA or CuDNN. I have RTX 3080 which does not work well with older CUDA and CuDNNs.

Thank you so much for this awesome work!!

**Comment by valerio-sanelli** [comment]
> Solved!! It is running perfectly on Colab
> 
> There is some issue with my laptop CUDA or CuDNN. I have RTX 3080 which does not work well with older CUDA and CuDNNs.
> 
> Thank you so much for this awesome work!!

Hello,
Can you please provide the Colab? 
Thanks
